create database btech_3A_114

create table BRANCH(

BNAME varchar(50),
CITY varchar(50),

)
INSERT INTO BRANCH VALUES('VRCE','NAGPUR')
INSERT INTO BRANCH VALUES('ANI','NAGPUR')
INSERT INTO BRANCH VALUES('KAROLBAGH','DELHI')
INSERT INTO BRANCH VALUES('CHANDI','DELHI')
INSERT INTO BRANCH VALUES('M.G.ROAD','NAGPUR')
INSERT INTO BRANCH VALUES('ANDHERI','BANGLORE')
INSERT INTO BRANCH VALUES('VIRAR','BOMBAY')
INSERT INTO BRANCH VALUES('NEHRU PLACE','BOMBAY')
INSERT INTO BRANCH VALUES('POWAI','BOMBAY')



SELECT * FROM BRANCH
create table COUSTMER(

CNAME varchar(50),
CITY varchar(50),

)
INSERT INTO COUSTMER VALUES('ANIL','CALCUTTA')
INSERT INTO COUSTMER VALUES('SUNIL','DELHI')
INSERT INTO COUSTMER VALUES('MEHUL','BARODA')
INSERT INTO COUSTMER VALUES('MANDAR','PATNA')
INSERT INTO COUSTMER VALUES('MADHURI','NAGPUR')
INSERT INTO COUSTMER VALUES('PRAMOD','NAGPUR')
INSERT INTO COUSTMER VALUES('SANDIP','SURAT')
INSERT INTO COUSTMER VALUES('SHIVANI','BOMBAY')
INSERT INTO COUSTMER VALUES('KRANTI','BOMBAY')
INSERT INTO COUSTMER VALUES('NAREN','BOMBAY')
SELECT * FROM COUSTMER